### ISSUE TITLE
Selected tests are not saved correctly

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#102]
Please ignore sound of video.  I think it's small bug.
https://drive.google.com/file/d/101XRbjhHRQ_mgnO49NC6sOcrdD5C86tQ/view

**Comment by AlexeyDmitriev** [comment]
Hi, @emli. I think the problem may be in the fact that all the test show "Test #0" instead of showing actual test number. I encountered this once myself but I have no idea how to reproduce this. If you have an idea how it happened and/or how to fix that, I'll be glad to hear that. 
Maybe you remember what you did before you get that problem?

**Comment by emli** [comment]
I can't reproduce again. It working now. But it's not worked when I need :)

**Comment by AlexeyDmitriev** [comment]
Let's have this open, maybe I can fix it if it's reproduced by somebody

**Comment by rishabhdeepsingh** [comment]
Is it still open?

**Comment by emli** [comment]
> Is it still open?

Passed 2 years.  Nobody reported I think we close.
