### ISSUE TITLE
Clean unused defines

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#104]
I wonder can jhelper can do it.  For example I many defines. Sometimes I use them and sometimes I am not. Let me know if it possible

**Comment by AlexeyDmitriev** [comment]
There's an option to remove unused code (check the settings) but it doesn't work very well (sometimes removing used code) because of how finding usages works (so I don't use it). 
I've never tested it with defines, it may work with them.

What I do is I split my code to smallish files so that amount of unused code is limited. I don't think I actually run into source limit since the time I use JHelper, so I don't care much about removing unused code

**Comment by emli** [comment]
Tested it removes used code
