### ISSUE TITLE
About include errors when using WSL

### ISSUE THREAD

**Issue by t11em** [AlexeyDmitriev/JHelper#113]
I am using JHelper with CLion WSL.

When JHelper is executed in this development environment,
#include "% TaskFile%" converted to Windows path,
An include error has occurred

Is there any workaround here?(Can it be converted to a unix path?)

**Comment by AlexeyDmitriev** [comment]
Do you mean the problem is in the \ vs / separators?

To be honest, I'm not really familiar with windows and WSL and don't have to access to one to investigate.

Any chance you can produce a patch that will work for you?
The path is produced [in this line](https://github.com/AlexeyDmitriev/JHelper/blob/8853af9dff42fa8112258868f5d632540e5834ca/src/name/admitriev/jhelper/generation/CodeGenerationUtils.java#L45)

**Comment by t11em** [comment]
Thank you for your reply !

> Do you mean the problem is in the \ vs / separators?

Yes. I think so.

> Any chance you can produce a patch that will work for you?

OK ! I'll try it.

**Comment by AlexeyDmitriev** [comment]
Fixed in 135a433.

Please let me know if it didn't help
