### ISSUE TITLE
Get the Test number # for codejam or kickstart 

### ISSUE THREAD

**Issue by Ziklon** [AlexeyDmitriev/JHelper#115]
The current **task.template** does not support testNumber.

```
void solve(int caseNumber, std::istream& in, std::ostream& out) {

}
```

**Comment by AlexeyDmitriev** [comment]
This behaviour can be emulated now: https://github.com/AlexeyDmitriev/JHelper/wiki/Adding-a-GCJ-style-output

I don't really want to merge it as proposed at the moment because
1) the variable is unused most of the time
2) it's easy to emulate
3) it will break compatibility for everybody (everybody will have to either delete their task.template or adopt it)

your thoughts?

**Comment by Ziklon** [comment]
I agree using the emulate way, 
resolving this.
