### ISSUE TITLE
How to contribute.

### ISSUE THREAD

**Issue by rishabhdeepsingh** [AlexeyDmitriev/JHelper#121]
Intellij Plugins are made using Gradle etc. But I can't find any setting here.
How do I contribute?

**Comment by AlexeyDmitriev** [comment]
Hi, rishabhdeepsingh 

Thanks for the interest to contribute.
gradle is indeed recommended for newer plugins but in JHelper the [legacy system (called DevKit)](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/using_dev_kit.html) is still used.

Note, it's better to name your SDK "CLion" (instead of default name containing version), in that case you should be able to use my .idea directory which is no repo

Please let me know, whether docs inked helps to configure the project.

**Comment by rishabhdeepsingh** [comment]
I guess we are using some old versions of dependencies.
I am having trouble finding versions of all.

**Comment by AlexeyDmitriev** [comment]
What kind of dependencies do you mean? I don't think there are any dependencies except chelper which is in the repo itself

**Comment by rishabhdeepsingh** [comment]
Q: Can we shift to Gradle Setting this up is really hard and requires a large amount of space for sources as well?

**Comment by AlexeyDmitriev** [comment]
I am ok with switching to gradle, you can send PR

**Comment by AlexeyDmitriev** [comment]
although I still wasn't able to understand what exactly is a problem with configuring devkit

**Comment by AlexeyDmitriev** [comment]
Gradle support is in master

**Comment by rishabhdeepsingh** [comment]
Thanks a lot for merging the PR
DevKit needs extra GitHub library of approx 2.5Gb
I was not able to add run configuration for the same.
