### ISSUE TITLE
How use global variable?

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#97]
Hi @AlexeyDmitriev

As you know CP programmers love use global variables. With jhelper we need reinitialize global variable.
What it the better solution for this situation?

**Comment by AlexeyDmitriev** [comment]
Well, you can use variables inside the class (they are initialized before each test (but not between tests in multitest) e.g

```
class TaskA {
   int global = 0; 

   void solve(...) {...}
};
```

But IMO they are not that useful, unless you have recursive functions

**Comment by emli** [comment]
```    int x;
        int a[100];
        auto f = [&]() {
            cout << x << endl;
            cout <<a[1] << " " << a[99] << endl;
        };
        f();

```

Variables getting random values by default.

**Comment by AlexeyDmitriev** [comment]
Hope that helps

**Comment by emli** [comment]
Hi @AlexeyDmitriev !

I think jhelper testing like this;

Solution solution;

solution.run() - calling this function many times. 

Why not make like this.

Solution solution_for_first_test,solution_for_second_test;

Initialize variables is not friendly not sport programming.

**Comment by AlexeyDmitriev** [comment]
Well, there's 3 reasons for this design I see:
1) This way it's easier to embed it to CLion: you have 1 task -- 1 application run as normally
2) This way it's easier to aggregate result of all runs: to check whether all outputs are correct, to print max time, etc
3) This way it's faster in case of multiple small tests because you don't need to have a startup time for each test.

Besides, I don't think multiprocess option gives an advantages because it's not that hard to initialise variables: just add {} to them. Maybe you are just used to global variables and not used

Maybe it may help to think of it this way: you are writing a function that should calculate something but you don't know when your function will be called. Maybe it's not the way one usually thinks when he writes only sport programming code, but I think it should be useful to try. For example, imagine you are a developer of standard library and need to implement a `std::sort` function. You may do anything you need in it (have variables, other functions) but after you return, input array should became sorted and nothing else should change.
It may seem like a big restriction but I don't think it really is. 
When also applied to subparts of the code, it also makes reasoning about the code easier. The same applies to classes, e.g if you have a class for segment tree and not use global variables, you can reuse it in the problem where you need 5 independent segment trees or apply to different algorithms that happen. You can find some inspiration in my spcppl library (e.g for your own library for contests).

Also, you may check my submissions e.g on CF and see that it happens quite rare that I actually use global variables (or equivalently, variable inside a solution class)

On somewhat unrelated note: I recommend to switch from arrays[MAXN] to vectors (I used arrays before too but switched eventually). It makes debugging much easier, especially if you use sanitizers or flags to debug vector access locally. Contrary to popular belief, it  (almost?) doesn't gives you a performance hit if used correctly (if you always create it with sizes when size is known, you may also see examples in my submissions).
Compare `int a[101010];` vs `vector<int> v(n);`. Not much longer(and letters easier to type than numbers)

**Comment by emli** [comment]
@AlexeyDmitriev thanks for well explained answer

**Comment by emli** [comment]
https://github.com/emli/competitive/blob/master/tasks/spoj/KeyTask.cpp#L32

Found another solution

**Comment by AlexeyDmitriev** [comment]
I am glad you find solution that suits you, but I don't really understand, what you win here compared to https://github.com/AlexeyDmitriev/jhelper-example-project/blob/patch-1/tasks/spoj/KeyTask.cpp

**Comment by AlexeyDmitriev** [comment]
PS: you can implement [reading till zeroes](https://github.com/AlexeyDmitriev/JHelper/wiki/Usage) so that solve() only needs to solve one subtest, not all of them

**Comment by emli** [comment]
Your solution is short and good. But minus is that you can't create big arrays in class. You should increase stack size in cmake file that actually I can't do it

**Comment by AlexeyDmitriev** [comment]
That's a problem I didn't think of. I think you can increase stack [like this](https://stackoverflow.com/a/2279084/768110) if you use linux/macosx in your run.template

**Comment by AlexeyDmitriev** [comment]
I don't think it's possible unless you are on windows
